%YAML 1.1
---
language: d
d: [dmd, ldc]
sudo: false
addons:
  apt:
    packages:
    - libevent-dev
before_install: [pip install --user codecov, dub fetch packageversion]
script: dub build --compiler=${DC} && dub test --compiler=${DC} --coverage -- -s -t -d && dub build --compiler=${DC} --build=ddox
after_success: codecov
